base_lr: 0.1
batch_size: 256
learning_rate: 0
LARS: True
cosine_decay_lr_momentum: True
min_lr: 0.0001
num_epochs: 20
weight_decay: 0.0001
momentum_start: 0.9
warmup_epochs: 10
model: resnet18
augmentation: normalization
use_wandb: True
pretrained: True
checkpoint_path:
num_classes: 1
loss: binary_cross_entropy_with_logits
mode: SL
dataset: crc
lambda: 0.005
accumulation_steps: 2
kind: RMS
seed: 42
augmentation_val: 
augmentation_test: 