base_lr: 0.1
batch_size: 64
learning_rate: 0
LARS: True
cosine_decay_lr_momentum: True
min_lr: 0.0001
num_epochs: 20
weight_decay: 0.0001
momentum_start: 0.9
warmup_epochs: 10
model: resnet18
augmentation: GeometricAugmentation
use_wandb: True
pretrained: False
checkpoint_path: /home/daviddrexlin/Master/model_checkpoints/crc-SL-GeometricAugmentation-LARS-cross_entropy-scratch-epoch=19-step=3520.ckpt
num_classes: 9
loss: cross_entropy
mode: SL
dataset: crc
lambda: 0.005
accumulation_steps: 8
kind: image_net
seed: 42
augmentation_val: 
augmentation_test: 